# Generated by Django 4.2.19 on 2025-02-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('complete_by', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(default=1)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
